name: npm install + test
on: 
  workflow_dispatch:

env:
  MYNPMVERSION: 14

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: do checkout 
        uses: actions/checkout@v3  
      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.MYNPMVERSION}}
      - name: run test
        shell: bash
        run: npm -v
      - name: run test
        shell: bash
        run: |
          npm install
          npm test
