name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: do checkout 
        uses: actions/checkout@v3  
      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: run test
        shell: bash
        run: |
          npm install
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: do checkout 
        uses: actions/checkout@v3  
      - name : setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
        - name: run test
          shell: bash
          run: |
            npm test