name: Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: my short sha calculation
        id: myshortsha
        run: |
          GITHUB_PR_SHA=${{github.event.pull_request.base.sha}}
          echo $GITHUB_PR_SHA
          echo "myshortsha=${GITHUB_SHA::10}" 
          echo "myshortsha=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT
      - name: myissue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/issues \
          --header 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{steps.short_sha.outputs.myshortsha}}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{github.workflow}}**. \n\n The commit hash was: _${{steps.short_sha.outputs.myshortsha}}_."
            }' \
          --fail